config/routes.rb
Rails.application.routes.draw do
  resources :widgets

  root to: 'welcome#index'

  get 'welcome/getstarted'

  get 'welcome/information'

  get 'welcome/minigame'

end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  # GET /welcome
  def index

  end

end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name, :description, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Filo</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag  '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag  '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>
</html>

app/views/welcome/getstarted.html.erb
<!DOCTYPE html> <html lang="en"> 

<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8" /> 
<meta name="viewport" content="width=device-width, initial-scale=1" /> 
<title>Registration Form</title> 
<style>*{margin:0;padding:0;} html,body,#wrapper{width:100%;height:100%;} iframe{border-radius:0 !important;} </style> 
</head> 
<body> 
<div id="wrapper" data-tf-widget="SGDAeWpx" data-tf-inline-on-mobile data-tf-medium="snippet" >
</div>
<script src="//embed.typeform.com/next/embed.js"></script> 
</body> 
</html>

</html>

app/views/welcome/index.erb
<html lang="en_US" dir="ltr" class="example">

<div class="jumbotron text-center">
  <div class="container">
    <a href="/" class="filo-logo">
      <img src="<%= asset_path('filo-logo.png') %>">
    </a>
    <h1>Filo</h1>
    <p>Covid Budgeting: for the students, by the students.</p>
    
    <ul class = "verticalButtons">
      <li class = "buttonSpacing">
      <a type="button" class="btn btn-lg btn-primary" href="https://github.com/SenihOk/HackBU22"><span class="glyphicon glyphicon-download"></span> Source on GitHub</a>
      </li>

      <li class = "buttonSpacing">
      <a type="button" class="btn btn-lg btn-primary" onclick= "document.getElementById('creators').scrollIntoView();"> <span class="glyphicon glyphicon-knight"></span> Meet the Creators </a>
      </li>

      <li class = "buttonSpacing">
      <a type="button" class="btn btn-lg btn-primary" href="https://filo-hackbu22.herokuapp.com/welcome/getstarted"> <span class="glyphicon glyphicon-send"></span> Get started </a>
      </li>
      
    </ul>
    
    

  </div>

  <div id = "creators"> 
    <h3 style="text-align:center;">Coded By<br> Christopher, Senih, Shaun</h3>
    <div class = "row">
      <img src="<%= asset_path('bingham.png') %>", class = "staff_pic"> 
      <img src="<%= asset_path('senih.png') %>", class = "staff_pic"> 
      <img src="<%= asset_path('shaun.png') %>", class = "staff_pic">
    </div>
    </div>

 </div>

app/views/welcome/information.html.erb
<!DOCTYPE html>
<html lang="en_US" dir="ltr" class="example"> 

<head>

</head>

<nav class="navbar navbar-default navbar-static-top navbar-inverse">
<div class="container">
    <ul class="nav navbar-nav" style="font-size:14px;">
      <li>
        <a href="/"><span class="glyphicon glyphicon-home"></span> Home</a>
      </li>
      <li>
        <a href="https://filo-hackbu22.herokuapp.com/welcome/minigame"><span class="glyphicon glyphicon-education"></span> Interactive</a>
      </li>
    <ul class="nav navbar-nav navbar-right">
</div>
</nav>


    <h1 style="text-align:center; padding:40px;"> Informational Links <span class = "glyphicon glyphicon-piggy-bank"> </span> <h1>
<body class = "infoClass"> 
    <h2 style="text-align:center; color: white;"> </h2>
<table>
<colgroup>
    <col style="color: white; width: 20em; margin-left: auto; margin-right: auto;">
</colgroup>
  <tr style="title">
    <td>Career Help</td>
    <td>Finance Help</td>
  </tr>
  <tr>
    <td> <a href="https://www.linkedin.com/jobs">Linkedin Job Board</a> </td>
    <td> <a href="https://www.chase.com/personal/banking/education">Chase Personal Banking and Budgeting</a> </td>
  </tr>
  <tr>
    <td> <a href="https://www.binghamton.edu/ccpd/student-employment/index.html">Part-time Student Jobs</a>  </td>
    <td> <a href="https://studentaid.gov/">FAFSA Application</a> </td>
  </tr>
  <tr> 
    <td> <a href="https://www.binghamton.edu/ccpd/documents/qrg-resources/effective-interviewing-rvs.pdf">Interview Advice</a> </td>
    <td> <a href="https://www.binghamton.edu/financial-aid/resources/">Binghamton Financial Aid Services</a> </td>
  </tr>
  <tr>
    <td> <a href="https://www.vmock.com/">Vmock Resume Builder</a> </td>
    <td> <a href="https://mint.intuit.com/blog/budgeting/tips/"> Mint Budgeting Tips</a> </td>
  </tr>
</table> 

</body>

</html>

app/views/welcome/minigame.html.erb
<!DOCTYPE html>
<html lang="en_US" dir="ltr" class="example"> 

<head>
  <title>Ruby Getting Started on Heroku</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag  '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag  '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js' %>
  <%= csrf_meta_tags %>
</head>

<body>
<nav class="navbar-default navbar-static-top navbar-inverse">
<div class="container">
    <ul class="nav navbar-nav">
      <li>
        <a href="/"><span class="glyphicon glyphicon-home"></span> Home</a>
      </li>
      <li >
        <a href="https://filo-hackbu22.herokuapp.com/welcome/information"><span class="glyphicon glyphicon-pushpin"></span> Resources</a>
      </li>
    <ul class="nav navbar-nav navbar-right">
</div>
</nav>
</body>

<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8" /> <meta name="viewport" content="width=device-width, initial-scale=1" /> <title>My typeform</title> <style>*{margin:0;padding:0;} html,body,#wrapper{width:100%;height:100%;} iframe{border-radius:0 !important;}
</style> 
</head> 
<body> 
<div id="wrapper" data-tf-widget="VuasBJe7" data-tf-inline-on-mobile data-tf-medium="snippet" >
</div> 
<script src="//embed.typeform.com/next/embed.js">
</script> 
</body> 
</html>

</html>

app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<div class="container">

<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

</div>

app/views/widgets/index.html.erb
<div class="container">
<h1>Listing widgets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.name %></td>
        <td><%= widget.description %></td>
        <td><%= widget.stock %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

</div>

app/views/widgets/new.html.erb
<div class="container">

<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

</div>

app/views/widgets/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @widget.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @widget.stock %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>

</div>